quoraforengg/myquora/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('question/add/', views.QuestionCreate.as_view(), name='question-add'),
    path('questions/', views.QuestionListView.as_view(), name='questions'),
    path('answers/', views.AnswerListView.as_view(), name='answers'),
    path('question/<int:pk>', views.QuestionDetailView.as_view(), name='question-detail'),
    path('question/<int:pk>/answer/', views.AnswerCreate.as_view(), name='answer-add'),
    path('question/<int:pk>/update/', views.UpdateQuestion.as_view(), name='question-update'),
    path('answer/<int:pk>/update/', views.UpdateAnswer.as_view(), name='answer-update'),
    path('answer/<int:pk>/comment/', views.CommentCreate.as_view(), name='comment-add'),
    path('answer/upvote/<int:pk>', views.UpvoteCreate.as_view(), name='answer-upvote'),
    path('answer/downvote/<int:pk>', views.DownvoteCreate.as_view(), name='answer-downvote'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    path('author/add/', views.AuthorCreate.as_view(), name='author-add'),
    path('author/<int:pk>/', views.AuthorUpdate.as_view(), name='author-update')
]

quoraforengg/quora/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myquora/', include('myquora.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='/myquora/')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quoraforengg/myquora/models.py
from django.contrib import admin
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone
# Create your models here.

class Author(models.Model):

    """Model representing an author."""
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    email = models.EmailField(max_length=70, blank=True)
    date_created = models.DateField(null=True, default=timezone.now())
    credits = models.IntegerField(default=0)

    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('author-detail', args=[str(self.id)])
        # return reverse('author-detail', kwargs={'pk': self.pk})
        # another way of doing this

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.user.username}'


class AuthorAdmin(admin.ModelAdmin):
    list_display = ('user', 'email', 'date_created', 'credits')


class Comment(models.Model):

    """Model representing a question."""
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    answer = models.ForeignKey('Answer', on_delete=models.SET_NULL, null=True)
    comment_text = models.TextField(max_length=1000, help_text='Enter your comment...')
    date_created = models.DateField(default=timezone.now())
    date_updated = models.DateField(default=timezone.now())

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.comment_text}'


class CommentAdmin(admin.ModelAdmin):
    list_display = ('comment_text', 'author', 'date_created')
    list_filter = ('date_created', 'author')


class Answer(models.Model):

    """Model representing a question."""
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True)
    question = models.ForeignKey('Question', on_delete=models.SET_NULL, null=True)
    answer_text = models.TextField(max_length=2000, help_text='Write your answer here...')
    date_created = models.DateField(null=True, default=timezone.now())
    date_updated = models.DateField(null=True, default=timezone.now())
    upvote = models.IntegerField(default=0)
    downvote = models.IntegerField(default=0)
    views = models.IntegerField(default=0)

    def __str__(self):
        """String for representing the Model object."""
        return f'Que: {self.question.question_text[:50]}.. Ans: {self.answer_text[:50]}..'


class AnswerAdmin(admin.ModelAdmin):
    list_display = (
        'question', 'answer_text', 'author', 'date_created', 'upvote', 'downvote', 'views')
    list_filter = ('date_created', 'author', 'upvote', 'downvote', 'views')
    fieldsets = (
        (None, {
            'fields': ('author','question', 'answer_text')
        }),
        ('Dates', {
            'fields': ('date_created', 'date_updated')
        }),
        ('Actions', {
            'fields': ('upvote', 'downvote', 'views')
        }),
    )


class Question(models.Model):

    """Model representing a question."""
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True)
    question_text = models.TextField(max_length=1000, help_text='Enter your question in brief')
    date_created = models.DateField(null=True, default=timezone.now())
    date_updated = models.DateField(null=True, default=timezone.now())

    def get_absolute_url(self):
        """Returns the url to access a particular question and its answer."""
        return reverse('question-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.question_text}'


class QuestionAdmin(admin.ModelAdmin):
    list_display = ('question_text', 'author', 'date_created')
    list_filter = ('date_created', 'author')

quoraforengg/myquora/views.py
from django.contrib.auth.hashers import PBKDF2PasswordHasher
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.shortcuts import redirect, render
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from myquora.models import Answer, Author, Comment, Question


class UpdateAnswer(LoginRequiredMixin, UpdateView):
    model = Answer
    fields = ['answer_text']
    template_name = 'myquora/answer_update_form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        answer_id = self.kwargs['pk']
        answer = Answer.objects.get(id=answer_id)
        self.pk = answer.question.id
        context['answer_text'] = answer.answer_text
        return context

    def get_success_url(self):
        return (reverse('question-detail', kwargs={'pk': self.object.question.id}))


class UpdateQuestion(LoginRequiredMixin, UpdateView):
    model = Question
    fields = ['question_text']
    success_url = reverse_lazy('questions')
    template_name = 'myquora/question_update_form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        question_id = self.kwargs['pk']
        question = Question.objects.get(id=question_id)
        context['question_text'] = question.question_text
        return context


class CommentCreate(LoginRequiredMixin, CreateView):
    model = Comment
    fields = ['author', 'answer', 'comment_text']

    def get(self, request, *args, **kwargs):
        a_id = self.kwargs['pk']
        return render(request, 'myquora/comment_form.html', {"a_id": a_id})

    def post(self, request, *args, **kwargs):
        comment_text = request.POST.get('comment_text')
        params = self.kwargs['pk']
        author = Author.objects.get(user=self.request.user)
        answer = Answer.objects.get(id=params)
        Comment.objects.create(
            author=author, answer=answer, comment_text=comment_text)
        response = redirect(
            reverse('question-detail', kwargs={'pk': answer.question.id}))
        return response


class UpvoteCreate(LoginRequiredMixin, CreateView):
    model = Answer
    fields = ['answer_text', 'id', 'upvote']

    def post(self, request, *args, **kwargs):
        answer_id = self.kwargs['pk']
        answer = Answer.objects.get(id=answer_id)
        answer.upvote += 1
        answer.save()
        response = redirect(
            reverse('question-detail', kwargs={'pk': answer.question.id}))
        return response


class DownvoteCreate(LoginRequiredMixin, CreateView):
    model = Answer
    fields = ['answer_text', 'id', 'downvote']

    def post(self, request, *args, **kwargs):
        answer_id = self.kwargs['pk']
        answer = Answer.objects.get(id=answer_id)
        answer.downvote += 1
        answer.save()
        response = redirect(
            reverse('question-detail', kwargs={'pk': answer.question.id}))
        return response


class QuestionCreate(LoginRequiredMixin, CreateView):
    model = Question
    fields = ['question_text', 'credits']

    def get(self, request, *args, **kwargs):
        return render(request, 'myquora/question_form.html')

    def post(self, request, *args, **kwargs):
        response = redirect('/myquora/questions')
        return response


class AnswerCreate(LoginRequiredMixin, CreateView):
    model = Answer
    fields = ['answer_text']

    def get(self, request, *args, **kwargs):
        q_id = self.kwargs['pk']
        return render(request, 'myquora/answer_form.html', {"q_id": q_id})

    def post(self, request, *args, **kwargs):
        answer_text = request.POST.get('answer_text')
        answer = Answer.objects.create(author=Author.objects.get(
            user=self.request.user), question=Question.objects.get(
                id=self.kwargs['pk']), answer_text=answer_text)
        response = redirect(reverse('question-detail', kwargs={'pk': answer.question.id}))
        return response


class AuthorCreate(CreateView):
    model = Author
    fields = ['email', 'credits']

    def get(self, request, *args, **kwargs):
        return render(request, 'myquora/author_form.html')

    def post(self, request, *args, **kwargs):
        username = request.POST.get('username')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        email = request.POST.get('email')

        if password1 == password2:
            hasher = PBKDF2PasswordHasher()
            password = hasher.encode(
                password=password1, salt='salt', iterations=150000)

            user = User.objects.create(username=username, password=password)
            Author.objects.create(user=user, email=email, )
            response = redirect('/accounts/login/')
            return response
        else:
            return render(request, 'myquora/author_form.html')


class AuthorUpdate(UpdateView):
    model = Author
    fields = ['email']


class AuthorDelete(DeleteView):
    model = Author
    fields = ['user']
    fields = ['email']
    fields = ['credits']
    success_url = reverse_lazy('questions')


class AuthorDetailView(generic.DetailView):
    """Generic class-based detail view for an Author."""
    model = Author


class QuestionDetailView(generic.DetailView):
    """Generic class-based detail view for a Question."""
    model = Question

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        question_id = self.kwargs['pk']
        question = Question.objects.get(id=question_id)
        answer_list = Answer.objects.filter(question=question)
        comment_dictionary = {
                ans.id: Comment.objects.filter(answer=ans) for ans in answer_list
            }
        context['answer_list'] = answer_list
        context['answer_url'] = '/myquora/question/'+str(question_id)+'/answer/'
        context['upvote_url'] = '/myquora/answer/upvote/'
        context['downvote_url'] = '/myquora/answer/downvote/'
        context['comment_dictionary'] = comment_dictionary
        return context


class AnswerListView(generic.ListView):
    model = Answer
    paginate_by = 3


class QuestionListView(generic.ListView):
    model = Question
    paginate_by = 10


def index(request):
    """View function for home page of site."""
    num_questions = Question.objects.all().count()
    num_answers = Answer.objects.all().count()
    num_authors = Author.objects.count()
    num_comments = Comment.objects.count()
    context = {
        'num_questions': num_questions,
        'num_answers': num_answers,
        'num_authors': num_authors,
        'num_comments': num_comments,
    }
    return render(request, 'index.html', context=context)

quoraforengg/myquora/templates/myquora/answer_form.html
{% extends "base_generic.html" %}

{% block content %}
<form action='/myquora/question/{{q_id}}/answer/' method="POST">
    {% csrf_token %}
    <label for="answer_text">Write your answer</label>
    <br>
    <br>
    <textarea name="answer_text" id="answer_text" cols="80" rows="10"></textarea>

    <br><br>
    <button type="submit" class="btn btn-primary">Answer</button>
</form>

{% endblock %}

quoraforengg/myquora/templates/myquora/answer_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>answer List</h1>
  {% if answer_list %}
  <ul>

    {% for answer in answer_list %}
      <div class="row text-info">
          &nbsp; {{ answer.question.question_text }}
      </div>
          <hr></hr>
        <div class="row text-dark">
          {{ answer.answer_text }}</a>
        </div>
        <br>
        <br>
        <div class="row text-success">
            <div class="col"></div>
            <div class="col-6"></div>
            <div class="col">
                by <a href="{{ answer.author.get_absolute_url }}">{{answer.author}} </a>
                (on {{answer.date_updated}})
            </div>
        </div>

    {% endfor %}
  </ul>
  {% else %}
    <p>There are no answers in the library.</p>
  {% endif %}
{% endblock %}

quoraforengg/myquora/templates/myquora/answer_update_form.html
{% extends "base_generic.html" %}

{% block content %}

    <form method="POST">
        <div class="form-group">
            {% csrf_token %}
        </div>

        <div class="form-group">
            <label for="id_answer_text">answer text:</label>
            <textarea class="form-control" name="answer_text" cols="40" rows="10" maxlength="1000" required id="id_answer_text">
                    {{answer_text}}
            </textarea>
            <br>
            <span class="helptext">Enter your answer in brief</span>
        </div>

        <button type="submit" class="btn btn-primary">Update</button>
    </form>

{% endblock %}

quoraforengg/myquora/templates/myquora/author_confirm_delete.html
<form action='/myquora/author/add/' method='post'>
    {% csrf_token %}
     {{ form.as_p }}

    <!-- <label for="email">Email</label> -->
    <!-- <input type="email" name="email" id="email"> -->
    <br><br>
    <button type="submit" class="btn btn-primary">Create</button>
</form>

quoraforengg/myquora/templates/myquora/author_detail.html
{% extends "base_generic.html" %}

{% block content %}

<hr></hr>
<h2>Author Details</h2>
<p>App has the following record counts:</p>
<ul>
        <li><strong>Authors:</strong> {{ author.user.username }}</li>
        <li><strong>Email:</strong> {{ author.email }}</li>
        <li><strong>Created on:</strong> {{ author.date_created }}</li>
        <li><strong>Credits:</strong> {{ author.credits }}</li>

</ul>
{% endblock %}

quoraforengg/myquora/templates/myquora/author_form.html
{% extends "base_generic.html" %}

{% block content %}
    <br>
    <form action='/myquora/author/add/' method='post'>
        {% csrf_token %}
        <div class="form-group">
        <label for="id_username">Username:</label>
        <input type="text" name="username"  class="form-control" autofocus required id="id_username">
        <span class="helptext">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</span>
        </div>
        <div class="form-group"></div>
        <label for="email">Your Email:</label>
        <input type="email" name="email" id="email"  class="form-control" aria-describedby="emailHelp" placeholder="Enter email" required>
        <div class="form-group">
            <label for="id_password1">Password:</label>
            <input type="password" name="password1" required id="id_password1" class="form-control" placeholder="Enter Password">
            <span class="helptext">
            <ul>
                <li>Your password can&#39;t be too similar to your other personal information.</li>
                <li>Your password must contain at least 8 characters.</li>
                <li>Your password can&#39;t be a commonly used password.</li>
                <li>Your password can&#39;t be entirely numeric.</li>
            </ul>
            </span>
        </div>
        <div class="form-group">
            <label for="id_password2">Password confirmation:</label>
            <input type="password" name="password2" required id="id_password2" class="form-control" placeholder="Confirm Password">
            <span class="helptext">Enter the same password as before, for verification.</span>
        </div>
        <button type="submit" class="btn btn-primary">Register</button>

    </form>

{% endblock %}

quoraforengg/myquora/templates/myquora/comment_form.html
{% extends "base_generic.html" %}


{% block content %}
<form action='/myquora/answer/{{a_id}}/comment/' method="post">

    {% csrf_token %}
    <label for="comment_text">Write your comment: </label>
    <br>
    <br>
    <textarea name="comment_text" id="comment_text" cols="80" rows="8" required></textarea>

    <br><br>
    <button type="submit" class="btn btn-primary">Comment</button>
</form>
{% endblock %}

quoraforengg/myquora/templates/myquora/question_detail.html
{% extends "base_generic.html" %}

{% block content %}
<div style="margin-left: 5px;" class="row text-info">
    <h3>Que: {{ question.question_text }} </h3>
</div>

  <div class="text-success">
    <div class="row">
        <div class="col">
          <form action = "{{answer_url}}" method = "GET" >
            <input type = "hidden" name = "q_id" value = {{q_id}} />
            <input type ="submit"  class="btn btn-success" role="button" value="Answer this question">
          </form>
        </div>
        <div class="col-5"></div>
        <div class="col">
          <strong>Author:</strong> <a href="{{ question.author.get_absolute_url }}">{{ question.author }}</a>
          <br>
          <strong>Created On:</strong> {{ question.date_created }}
        </div>
    </div>

  <div style="margin-left:20px;margin-top:10px; margin-right: 10px;">

    {% if answer_list %}
    <ul>
        <h4>All Answers</h4>
      {% for answer in answer_list %}
          <br>
          <div class="card">
            <div class="card-body">
              {% comment %} <h5 class="card-title">Special title treatment</h5> {% endcomment %}
              <p class="card-text">
                <div class="row text-dark">
            {{ answer.answer_text }}
          </div>
          <br>
          <br>
          <div class="row text-success">

            <!-- upvote form -->
              <div class="col">
                <form action="{{upvote_url}}{{answer.id}}" method="POST">
                  {% csrf_token %}
                  <input type="submit" value="Upvote" class="btn btn-primary">
                  <span class="text-dark">{{ answer.upvote }}</span>
                </form>
              </div>

            <!-- downvote form -->
            <div class="col">
                <form action="{{downvote_url}}{{answer.id}}" method="POST">
                  {% csrf_token %}
                  <input type="submit" value="Downvote" class="btn btn-primary">
                  <span class="text-dark">{{ answer.downvote }}</span>
                </form>
              </div>


            <!-- comment form -->
            <div class="col">
                <form action="/myquora/answer/{{answer.id}}/comment/" method="GET">
                  {% csrf_token %}
                  <input type="submit" value="Comment" class="btn btn-primary">
                </form>
            </div>

            {% comment %} update answer {% endcomment %}
            <div class="col-4">
            {% if user.is_authenticated %}
              {% if  user.get_username  ==  answer.author.user.username  %}
                  <a href="/myquora/answer/{{answer.id}}/update/" class="btn btn-primary">Update Answer</a>
              {% endif %}
            {% endif %}
            </div>
            <div class="col-3">
                  by <a href="{{ answer.author.get_absolute_url }}">{{answer.author}} </a>
                  (on {{answer.date_updated}})
            </div>

              </p>
              {% comment %} <a style="padding: 3px;" class="btn-success" href="/myquora/question/{{question.id}}/update/">Update Question</a> {% endcomment %}

            </div>
          </div>
 </div>

 <div style="margin-left: 20px;">
        <br>
        <ul class="list-group">
          {% for key, comment in comment_dictionary.items %}
            {% if key == answer.id %}
              {% if comment %}
                {% for comm in comment %}

                    <li class="list-group-item disabled">{{ comm }}</li>

                {% endfor %}
              {% endif %}
            {% endif %}
          {% endfor %}
        <ul>
        </div>
      {% endfor %}
    </ul>
    {% else %}

    <div class="text-danger">
        There are no answers for this question.
    </div>

    {% endif %}

  </div>
{% endblock %}

quoraforengg/myquora/templates/myquora/question_form.html
{% extends "base_generic.html" %}


{% block content %}
<form action='/myquora/question/add/' method="post">

    {% csrf_token %}
    <label for="question_text">Question Title: </label>
    <br>
    <br>
    <textarea name="question_text" id="question_text" cols="80" rows="10" required></textarea>

    <br><br>
    <button type="submit" class="btn btn-primary">Ask</button>
</form>
{% endblock %}

quoraforengg/myquora/templates/myquora/question_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Question List</h1>
  {% if question_list %}
  <ul class="list-group">
    {% for question in question_list %}
      <li style="padding: 4px; margin: 3px; list-style: none; text-decoration: none;" class="list-group-item list-group-item-action list-group-item-dark">
        <a style="text-decoration: none; color: black" href="{{ question.get_absolute_url }}">{{ question.question_text }}</a>
        &nbsp; &nbsp; &nbsp;
        by
        <a style="text-decoration: none; color: black;" href="{{ question.author.get_absolute_url }}"> {{question.author}} </a>
        (on {{question.date_updated}})

        {% if user.is_authenticated %}
            {% if  user.get_username  ==  question.author.user.username  %}
                <a style="padding: 3px; text-decoration: none;" class="btn btn-primary" href="/myquora/question/{{question.id}}/update/">Update Question</a>
            {% endif %}
        {% endif %}

      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no questions in the library.</p>
  {% endif %}
{% endblock %}

quoraforengg/myquora/templates/myquora/question_update_form.html
{% extends "base_generic.html" %}


{% block content %}

<form method="POST">

    <div class="form-group">
        {% csrf_token %}
    </div>

    <div class="form-group">
        <label for="id_question_text">Question text:</label>
        <textarea class="form-control" name="question_text" cols="10" rows="10" maxlength="1000" required id="id_question_text">
                {{question_text}}
        </textarea>
        <br>
        <span class="helptext">Enter your question in brief</span>
    </div>


    <button type="submit" class="btn btn-primary">Update</button>
</form>


{% endblock %}